### ISSUE TITLE
Error on writing on InfluxDB

### ISSUE THREAD

**Issue by tutunci** [shunfei/DCMonitor#20]
Hi,
I've installed DCMonitor and InfluxDb 0.9 RC 30
Looking at logs I see:
2015-05-14 18:11:29,369 ERROR [Thread-3] com.sf.influxdb.impl.InfluxDBImpl - database: [dcmonitor], retentionPolicy: [], points: [16]
java.lang.RuntimeException: {"error":"field \"size\" is type string, mapped as type number"}

2015-05-14 18:11:34,457 ERROR [Thread-3] com.sf.influxdb.impl.InfluxDBImpl - database: [dcmonitor], retentionPolicy: [], points: [16]
java.lang.RuntimeException: {"error":"field \"offs\" is type string, mapped as type number"}

and so on

Can you please specify which InfluxDB version  (RC version) you used?

Thanks

**Comment by flowbehappy** [comment]
Hi @tutunci , sorry for delay replay. 
We are using [v0.9.0-rc30: Release RC30](https://github.com/influxdb/influxdb/releases/tag/v0.9.0-rc30) currently, try update to that release should help you out. And remember to remove all old data in your broker.dir and data.dir update update InfluxDB, it seems that they are not compatible between rc releases.

**Comment by tutunci** [comment]
It's now working as expected. 
Thanks a lot!!

Any plan about Druid section, I'm really interested on it.

Thanks
Maurizio

**Comment by flowbehappy** [comment]
@tutunci We are working on it, currently the metrics fetching & http api parts are finished, next progress is the web ui part.

**Comment by tutunci** [comment]
Great to hear this !!!

Thanks a lot!

**Comment by sundy-li** [comment]
BTW, any merge request are all welcome~
