### ISSUE TITLE
Graph not displayed 

### ISSUE THREAD

**Issue by tutunci** [shunfei/DCMonitor#27]
Hi,
I've updated my version of DCMonitor, now I'm able to see Druid section, really awesome.
Now I've an issue on Kafka graphs, it's not displayed.
My current version of InfluxDB is  0.9.0-rc30 .
Looking at InfluxDB logs I can see that read and write are done but when running the query an error occur like below: 

> select size, offs, lag from kafka_metrics where consumer='druid' and topic='buck_bidding' and partition='-1' and time >= '2015-07-23T15:25:32.665Z' and time <= '2015-07-23T15:40:32.665Z' group by topic, consumer
> ERR: measurement not found: "dcmonitor"..kafka_metrics (/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tx.go:60)

looking at tables I didn't see kafka_metrics, instead I can see kafka_consume.

> select size, offs, lag from kafka_consume where consumer='druid' and topic='buck_bidding' and partition='-1' and time >= '2015-07-23T15:25:32.665Z' and time <= '2015-07-23T15:40:32.665Z' group by topic, consumer
> name: kafka_consume
> tags: consumer=druid, topic=buck_bidding
> time    size    offs    lag
> ---

How can I fix this issue?

Thanks
Maurizio

**Comment by flowbehappy** [comment]
Hi @tutunci , 
If you are using latest DCMonitor release, i.e. [v0.1.2-rc](https://github.com/shunfei/DCMonitor/releases/tag/v0.1.2-rc), you should upgrade your InfluxDB to a stable 0.9 version, e.g. v0.9.0 or newer.  Try https://influxdb.com/docs/v0.9/introduction/installation.html. 

0.9.0-rc30 is older then 0.9.0, and as long as I know, there are big changes between 0.9 rcs so they could be incompatible. So you may have to remove the old metrics data(`meta.dir`, `data.dir`, `hinted-handoff.dir`) if encounter InfluxDB problem. And after upgraded your InfluxDB, you can restart DCMonitor to automatically create a database.

Hope this help.

**Comment by tutunci** [comment]
Hi @flowbehappy,
I've now installed InfluxDB 0.9.2 version.
I've dropped database and created from scratch, now looking on InfluxDB logs I see these lines:
[http] 2015/07/28 04:51:47 10.200.6.5 - - [28/Jul/2015:04:51:47 -0400] POST /write?u=root&p=root&db=dcmonitor&rp=&precision=n&consistency=one HTTP/1.1 400 86 - Java1.7.0_45 e15bbe90-3505-11e5-b967-000000000000 1.275462ms

Http error code is 400, so something is wrong and writes doesn't happen, did you have an example of the write query (it's on POST so I'm not able to see parameters) so I can check doing it manually.

Thanks for your help

Maurizio

**Comment by flowbehappy** [comment]
@tutunci Currently the InfluxDB 0.9.2 seems broken, as long as its document.
As the v0.1.2-rc mainly add the Druid nodes view, you can try this:
1. roll back your DCMonitor to the last stable version, like v0.1.1, and also rollback InfluxDB to [v0.9.0-rc30: Release RC30](https://github.com/influxdb/influxdb/releases/tag/v0.9.0-rc30).
2. If you really need the Druid view, you can keep DCMonitor v0.1.2-rc instance beside the main DCMonitor v0.1.1. Remember using a different `server.port` in `application.properties` and different log path in `log4j.xml` if deploy on same host.

Sorry for the inconvenience, we will publish a new version very soon with dropping InfluxDB.

**Comment by flowbehappy** [comment]
@tutunci  Now we have a new release [https://github.com/shunfei/DCMonitor/releases/tag/v0.1.3](https://github.com/shunfei/DCMonitor/releases/tag/v0.1.3), InfluxDB is replaced by [prometheus](http://prometheus.io/). Has been running in our production environment for days and works well.

**Comment by tutunci** [comment]
Hi guys,
great job, I'm going to install it asap.

Thanks
Maurizio
