### ISSUE TITLE
InfluxDB will be replaced in next release

### ISSUE THREAD

**Issue by flowbehappy** [shunfei/DCMonitor#28]
I'm really tired of InfluxDB!
From my experience, is very unstable, highly resource usage(CPU, disk IO), and the java client is not developer friendly. Since DCMonitor is mean to be a light weight tool, it should be easy to use, maintain and resource restraint. But relying on InfluxDB makes things difficult. 
Luckily the history metric storage is only used like a k-v storage with time range and group by, there are lots of storage system can handle this.
Maybe the good old mysql is a nice option.

**Comment by tutunci** [comment]
Hi,
I agree with you that InfluxDB even than potentially interesting has so many issues that make us loose time.
My personal experience on using Redis is very positive but thinking about DCMonitor that is strictly connected to Druid, why not using Druid itself as storage?
Moreover Druid allow to have HTTP Metrics emitter and should be nice that future version of DCMonitor can show Kafka graphs and Druid too :-)

Unfortunately I'm not a Java developer, but everything I can do to help you ... just ask

Thanks
Maurizio

**Comment by sundy-li** [comment]
Since druid is not easy to deploy and most users of this tool are  just to monitor the kafka producer  rate and consumer rate, to make DcMonitor to be a light weight tool, we like use common and easy database.
