### ISSUE TITLE
zk集群和kafka监控问题

### ISSUE THREAD

**Issue by chuckpu** [shunfei/DCMonitor#30]
请问能配置多个zookeeper集群吗？比如2181的集群和2191的集群
还有zk监控有很多unknown的现实不知道是为什么
kafka监控能支持kafka0.7吗

谢谢

**Comment by flowbehappy** [comment]
hi，目前还不能配置多个zk集群，你目前可以配置多个monitor实现。zk的unknown是函数返回的默认值，可以认为是无意义的项目。0.7版本的kafka还未经过测试。
