### ISSUE TITLE
zk地址配置问题

### ISSUE THREAD

**Issue by inter12** [shunfei/DCMonitor#41]
kafka和zk用的是同一个地址 adds
例如kafka的存储路径是 xx.com:2181/file/path

这个地址也被用到了zk的监控中，就解析失败。

需要考虑下kafka数据不是在默认zk路径下的问题

**Comment by sundy-li** [comment]
@inter12  
kafka客户端 只需要指定 consumer_group ,偏移存在zk对应的路径,目前没有自定义根路径的kafka配置提供
