### ISSUE TITLE
How to notify by email once kafka lag is over specific size

### ISSUE THREAD

**Issue by zousheng** [shunfei/DCMonitor#43]
Hi shunfei,

I tried to configure  the lag notification as below, but it failed, I dont get any email, I am not sure where I missed. Would you please help advise how to config it? thanks

"kafka": {
        "warning": true,
        "warnDefaultLag": 1000,
        "warnLagSpec": {
            "test|statistics": 1000
        },
        "@ignoreConsumerRegex": "set ignoreConsumerRegex to ignore sending warning on those test consumers",
        "ignoreConsumerRegex": "^console-consumer-.+$",
        "stormKafkaRoot": "/storm_kafka"
    },
    "notify": {
        "doSend": true,
        "appName": "kafka",
        "url": "http://notify.com",
        "emails": ["zouyu12344444@126.com"],
        "phones": []
    },

**Comment by sundy-li** [comment]
I am sorry，the notify feature is private  for the moment，the public notify server is under developing..

来自 魅蓝 note 2

-------- 原始邮件 --------
发件人：邹晟 notifications@github.com
时间：周一 7月18日 11:39
收件人：shunfei/DCMonitor DCMonitor@noreply.github.com
主题：[shunfei/DCMonitor] How to notify by email once kafka lag is over specific size (#43)

**Comment by zousheng** [comment]
Got it, thanks. Wish the public version be released soon.
